; PlatformIO Project Configuration File
; EEZYbotARM Mk2 - Root Monorepo Configuration

[platformio]
default_envs = esp32doit-devkit-v1
src_dir = firmware/src
include_dir = firmware/include
lib_dir = firmware/lib
test_dir = firmware/test
data_dir = firmware/data

[env:esp32doit-devkit-v1]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200
test_framework = unity
lib_ldf_mode = deep+
lib_deps =
    Wire
    SPI
    adafruit/Adafruit PWM Servo Driver Library @ ^3.0.2
